{% set name = "filelock" %}
{% set version = "3.13.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b319f24340b51f55a2bf7a12ac0755a9b03e718311dac567a0f4f7fabd2f5de

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python
    - hatchling 1.18
    - hatch-vcs 0.3
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - filelock
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tox-dev/py-filelock
  license: Unlicense
  license_family: Public-Domain
  license_file: LICENSE
  summary: A platform independent file lock.
  description: |
    A filelock provides a synchronisation mechanism between different
    instances of your application, similar to a thread lock. It can be
    used to signalize that files, directories or other resources are
    currently used or manipulated (Think of a sync.lock file). Only the
    existence of the lockfile is watched for this purpose. The file itself
    can not be written and is always empty.
  doc_url: https://py-filelock.readthedocs.io/
  dev_url: https://github.com/tox-dev/py-filelock

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
