{% set name = "filelock" %}
{% set version = "3.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cd540a9352e432c7246a48fe4e8712b10acb1df2ad1f30e8c070b82ae1fed85

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools >=41.0.0
    - wheel >=0.30.0
    # needed to get correct version number in the metadata
    - setuptools_scm >=2
  run:
    - python >=3.7

test:
  imports:
    - filelock
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tox-dev/py-filelock
  license: Unlicense
  license_family: Public-Domain
  license_file: LICENSE
  summary: A platform independent file lock.

  description: |
    A filelock provides a synchronisation mechanism between different
    instances of your application, similar to a thread lock. It can be
    used to signalize that files, directories or other resources are
    currently used or manipulated (Think of a sync.lock file). Only the
    existence of the lockfile is watched for this purpose. The file itself
    can not be written and is always empty.
  doc_url: https://py-filelock.readthedocs.io/en/latest/
  dev_url: https://github.com/tox-dev/py-filelock
  doc_source_url: https://github.com/tox-dev/py-filelock/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
