travis:
  secure:
    BINSTAR_TOKEN: bXHeGAchcL6BL0oFoughKnewz0q58bGFMR8klOnmhEXk64ELRIlUaAwgaJm+fSYfE3Eg1ywvgMUsvwh+68wY9WMMurJIhE6w5PpCW/tKQielaob+0thpy/B9FL01bQ7o/IpDtyzUWxZZSk4Cv8IbmTo0ByHQSrPCQ7fOOUonjA9HbEQrmHHZdmhP8iW9o34HO1+jdAkSiT3oTrPkyzT7r3vJCBsu5g/f1FbGgNYgM4G9PfjmcZ66fDiSLl5Q8PMrXWWfRNcaR64Z12BKtq8M8mAsettyIKTFtHvaohvfOhTM8qJEOUokiCBVDcVBx+lo+a46I7rXJURsyIfwK8NumUuF4JcCeUCb3wvqijMHxrBDuY2XalKOZhnLYbKDY9hX975ow3MDmyRCeRuSqZVHQ5xES/t3VN1v46V3wohKDVUFXCgbqQJQ97CYKTegzyMQpEK2yMyrc7jmxpdkXbDp6gW/6mGjccRO7/jYe6jeHf48kqcyc6+XnHWP/xO7MiKB0CRo8hPhQGIaYLYz7aORx7VPJRGXJsX5Xg2adqQxBb72Ixs6W1XADatJ/flAfRNXe2BBgWG1HpDBlPXlRdcjsTk6/SpnHbKVYHhxbo5lkZlKIcqSBjXeTrM4bRjWgnXBRt2VnHw0ykBavSNaRyo9Vg/p2Q+9sbq9BKD7S8MkwAw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
