travis:
  secure:
    BINSTAR_TOKEN: Q1kkD6GDqqkbQhCIK+BzMhg+ST9hj8KkHMR3wpOB1QWtymVM83TkZ5K2lAnirbHTZch3IFSNj57sq5TxQ2LgVIE3T4qbO+fFKXt/E3RSIntxJHknKvDiQrfF9iT/E/WyolNQt4Dri5FPGv9UicI3SY+xwBp/0G6dQu1OKO6sZ8jrSe+HQ75I3mRKn4UCh8r0ns2GBUcn7/1r5Bq5U0kBDMnyy7fhYfRjPcF4D6rzdT+GmMagoL9qfzUXLaA0M38gi+cHuA0AiUwTlXLM/CVfdTIcfRLK3ytu42XMNJ5EHr3Ap4nwaiFZumpf68+1uhWGzUiT7Gxdgc/+nJQ7TrL2V6HLS/ybkC135RgsIh6lIEja04HherJnfcEgBeE1y/SoTMuS7qFOtODHu+ngMuipekcdh6H2bNeOkKkq/naMD8x9fwYuLRMGnIL9XT+b7uj0eCLy1AK1rg7V1qKz2WmkzFKkkSYcI+2DS7LaE8iiyqkKs3Vi8erW8Jgt2jZ//UQjDBDUvqosOMQWIuLsaZiVVvN/zx302t0/5lYWjPmETYLqdvXZ7/F7go8RpGhEu85fSBzAL4zmEow57WRcNfG3A5ocm61uQ96LLkxbtg2ldzXkCaRzNSE9zwbEd+r6H7enD6fRp/dpzANgVFEreCYf5qOl+FKNR0YEgnTloc42MSU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
